In [1]:
!pip install tensorflow==2.15.1

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.3/475.3 MB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 59.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 74.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 97.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 25.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 5.1 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.2
    Uninstalling wrapt-1.17.2:
      Successfully uninstalled wrapt-1.17.2
  Attempting uninstall: keras
    Found existing installation: keras 3.8.0
    Uninstalling keras-3.8.0:
      Successfully uninstalled keras-3.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.18.0
    Uninstalling tensorboard-2.18.0:
      Successfully uninstalled tensorboard-2.18.0
  Attempting uninstall: ml-dtypes
    Found existing ins

In [2]:
!pip install -q tensorflow-recommenders
!pip install -q --upgrade tensorflow-datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.2/96.2 kB 140.2 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 43.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.9/319.9 kB 21.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.15.1 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 5.29.5 which is incompatible.
google-api-core 1.34.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<4.0.0dev,>=3.19.5, but you have protobuf 5.29.5 which is incompatible.
google-cloud-translate 3.12.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 5.29.5 which is incompatible.
tensorflow-decision-forests 1.11.0 requires tensorf

In [3]:
import os
import pprint
import tempfile

from typing import Dict, Text

import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds

2025-06-25 04:48:06.446067: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-06-25 04:48:06.446135: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-06-25 04:48:06.447798: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [4]:
tf.__version__

'2.15.1'

In [5]:
import tensorflow_recommenders as tfrs

In [6]:
# Ratings data.
ratings = tfds.load("movielens/100k-ratings", split="train")
# Features of all the available movies.
movies = tfds.load("movielens/100k-movies", split="train")

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/1 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/movielens/100k-ratings/incomplete.O598GN_0.1.1/movielens-train.tfrecord*..…

Dataset movielens downloaded and prepared to /root/tensorflow_datasets/movielens/100k-ratings/0.1.1. Subsequent calls will reuse this data.


Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/1 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/movielens/100k-movies/incomplete.2GEEX5_0.1.1/movielens-train.tfrecord*...…

Dataset movielens downloaded and prepared to /root/tensorflow_datasets/movielens/100k-movies/0.1.1. Subsequent calls will reuse this data.


In [7]:
for x in ratings.take(1).as_numpy_iterator():
  pprint.pprint(x)

{'bucketized_user_age': 45.0,
 'movie_genres': array([7]),
 'movie_id': b'357',
 'movie_title': b"One Flew Over the Cuckoo's Nest (1975)",
 'raw_user_age': 46.0,
 'timestamp': 879024327,
 'user_gender': True,
 'user_id': b'138',
 'user_occupation_label': 4,
 'user_occupation_text': b'doctor',
 'user_rating': 4.0,
 'user_zip_code': b'53211'}


In [8]:
for x in movies.take(1).as_numpy_iterator():
  pprint.pprint(x)

{'movie_genres': array([4]),
 'movie_id': b'1681',
 'movie_title': b'You So Crazy (1994)'}


In [9]:
ratings = ratings.map(lambda x: {
    "movie_title": x["movie_title"],
    "raw_user_age": x["raw_user_age"],
    "user_id": x["user_id"],
})
movies = movies.map(lambda x: x["movie_title"])

In [10]:
for x in ratings.take(1).as_numpy_iterator():
  pprint.pprint(x)

{'movie_title': b"One Flew Over the Cuckoo's Nest (1975)",
 'raw_user_age': 46.0,
 'user_id': b'138'}


In [11]:
for x in movies.take(1).as_numpy_iterator():
  pprint.pprint(x)

b'You So Crazy (1994)'


In [12]:
tf.random.set_seed(42)
train = ratings.shuffle(100_000, seed=42, reshuffle_each_iteration=False)

In [13]:
movie_titles = movies.batch(1_000)
user_ids = ratings.batch(1_000_000).map(lambda x: x["user_id"])

unique_movie_titles = np.unique(np.concatenate(list(movie_titles)))
unique_user_ids = np.unique(np.concatenate(list(user_ids)))

unique_movie_titles[:10]

array([b"'Til There Was You (1997)", b'1-900 (1994)',
       b'101 Dalmatians (1996)', b'12 Angry Men (1957)', b'187 (1997)',
       b'2 Days in the Valley (1996)',
       b'20,000 Leagues Under the Sea (1954)',
       b'2001: A Space Odyssey (1968)',
       b'3 Ninjas: High Noon At Mega Mountain (1998)',
       b'39 Steps, The (1935)'], dtype=object)

In [14]:
len(unique_user_ids)

943

In [15]:
embedding_dimension = 32

In [16]:
user_model = tf.keras.Sequential([
  tf.keras.layers.StringLookup(
      vocabulary=unique_user_ids, mask_token=None),
  # We add an additional embedding to account for unknown tokens.
  tf.keras.layers.Embedding(len(unique_user_ids) + 1, embedding_dimension)
])

In [17]:
movie_model = tf.keras.Sequential([
  tf.keras.layers.StringLookup(
      vocabulary=unique_movie_titles, mask_token=None),
  tf.keras.layers.Embedding(len(unique_movie_titles) + 1, embedding_dimension)
])

In [18]:
# Preformance
metrics = tfrs.metrics.FactorizedTopK(
  candidates=movies.batch(128).map(movie_model)
)

In [19]:
# Loss
task = tfrs.tasks.Retrieval(
  metrics=metrics
)

In [20]:
class MovielensModel(tfrs.Model):
  def __init__(self, user_model, movie_model):
    super().__init__()
    self.movie_model: tf.keras.Model = movie_model
    self.user_model: tf.keras.Model = user_model
    self.task: tf.keras.layers.Layer = task

  def compute_loss(self, features: Dict[Text, tf.Tensor], training=False) -> tf.Tensor:
    # We pick out the user features and pass them into the user model.
    user_embeddings = self.user_model(features["user_id"])
    # And pick out the movie features and pass them into the movie model,
    # getting embeddings back.
    positive_movie_embeddings = self.movie_model(features["movie_title"])

    # The task computes the loss and the metrics.
    return self.task(user_embeddings, positive_movie_embeddings)

In [21]:
retrival_model = MovielensModel(user_model, movie_model)
retrival_model.compile(optimizer=tf.keras.optimizers.Adagrad(learning_rate=0.1))

In [22]:
cached_train = train.shuffle(100_000).batch(8192).cache()

In [23]:
retrival_model.fit(cached_train, epochs=3)

Epoch 1/3
13/13 [==============================] - 20s 1s/step - factorized_top_k/top_1_categorical_accuracy: 0.0016 - factorized_top_k/top_5_categorical_accuracy: 0.0117 - factorized_top_k/top_10_categorical_accuracy: 0.0244 - factorized_top_k/top_50_categorical_accuracy: 0.1114 - factorized_top_k/top_100_categorical_accuracy: 0.1960 - loss: 64313.0499 - regularization_loss: 0.0000e+00 - total_loss: 64313.0499
Epoch 2/3
13/13 [==============================] - 16s 1s/step - factorized_top_k/top_1_categorical_accuracy: 0.0026 - factorized_top_k/top_5_categorical_accuracy: 0.0181 - factorized_top_k/top_10_categorical_accuracy: 0.0362 - factorized_top_k/top_50_categorical_accuracy: 0.1607 - factorized_top_k/top_100_categorical_accuracy: 0.2793 - loss: 62154.7160 - regularization_loss: 0.0000e+00 - total_loss: 62154.7160
Epoch 3/3
13/13 [==============================] - 18s 1s/step - factorized_top_k/top_1_categorical_accuracy: 0.0032 - factorized_top_k/top_5_categorical_accuracy: 0.0206

In [24]:
retrival_model.evaluate(cached_train, return_dict=True)

13/13 [==============================] - 15s 1s/step - factorized_top_k/top_1_categorical_accuracy: 0.0044 - factorized_top_k/top_5_categorical_accuracy: 0.0281 - factorized_top_k/top_10_categorical_accuracy: 0.0537 - factorized_top_k/top_50_categorical_accuracy: 0.2060 - factorized_top_k/top_100_categorical_accuracy: 0.3349 - loss: 60605.5315 - regularization_loss: 0.0000e+00 - total_loss: 60605.5315


{'factorized_top_k/top_1_categorical_accuracy': 0.004410000052303076,
 'factorized_top_k/top_5_categorical_accuracy': 0.02806999906897545,
 'factorized_top_k/top_10_categorical_accuracy': 0.05372999981045723,
 'factorized_top_k/top_50_categorical_accuracy': 0.20601999759674072,
 'factorized_top_k/top_100_categorical_accuracy': 0.33491000533103943,
 'loss': 11427.134765625,
 'regularization_loss': 0,
 'total_loss': 11427.134765625}

In [25]:
# Create a model that takes in raw query features, and
index = tfrs.layers.factorized_top_k.BruteForce(retrival_model.user_model)
# recommends movies out of the entire movies dataset.
index.index_from_dataset(
  tf.data.Dataset.zip((movies.batch(100), movies.batch(100).map(retrival_model.movie_model)))
)

# Get recommendations, user 42
_, titles = index(tf.constant(["42"]))
print(f"Recommendations for user 42: {titles[0, :3]}")

Recommendations for user 42: [b'Rudy (1993)' b'Just Cause (1995)' b'Indian in the Cupboard, The (1995)']


In [26]:
titles

<tf.Tensor: shape=(1, 10), dtype=string, numpy=
array([[b'Rudy (1993)', b'Just Cause (1995)',
        b'Indian in the Cupboard, The (1995)',
        b'Murder in the First (1995)',
        b'Father of the Bride Part II (1995)',
        b'Jungle Book, The (1994)', b'Client, The (1994)',
        b'Man Without a Face, The (1993)',
        b'Angels in the Outfield (1994)', b'Lion King, The (1994)']],
      dtype=object)>

In [27]:
tf.strings.length(titles)

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[11, 17, 34, 26, 34, 23, 18, 30, 29, 21]], dtype=int32)>

In [28]:
# Get recommendations, user 2
_, titles = index(tf.constant(["2"]))
print(f"Recommendations for user 2: {titles[0, :3]}")

Recommendations for user 2: [b'A Chef in Love (1996)' b'Kolya (1996)' b'Beautiful Thing (1996)']


In [29]:
titles

<tf.Tensor: shape=(1, 10), dtype=string, numpy=
array([[b'A Chef in Love (1996)', b'Kolya (1996)',
        b'Beautiful Thing (1996)', b"Ulee's Gold (1997)",
        b"Ulee's Gold (1997)", b'Restoration (1995)',
        b'Secrets & Lies (1996)', b'Shall We Dance? (1996)',
        b'Wild Reeds (1994)', b'Brassed Off (1996)']], dtype=object)>

In [30]:
# Get recommendations, user 200
_, titles = index(tf.constant(["200"]))
print(f"Recommendations for user 200: {titles[0, :3]}")

Recommendations for user 200: [b"Kid in King Arthur's Court, A (1995)"
 b'Homeward Bound II: Lost in San Francisco (1996)'
 b"Pete's Dragon (1977)"]


In [31]:
titles

<tf.Tensor: shape=(1, 10), dtype=string, numpy=
array([[b"Kid in King Arthur's Court, A (1995)",
        b'Homeward Bound II: Lost in San Francisco (1996)',
        b"Pete's Dragon (1977)", b'Goofy Movie, A (1995)',
        b'101 Dalmatians (1996)', b'First Kid (1996)', b'Casper (1995)',
        b'Jungle Book, The (1994)',
        b'Aladdin and the King of Thieves (1996)',
        b'Angels in the Outfield (1994)']], dtype=object)>